### ISSUE TITLE
Requesting a Release of new version (v2), with "install -y"

### ISSUE THREAD

**Issue by kpadalkar** [Joel-hanson/django-aws-eb-deploy#16]
**Is your feature request related to a problem? Please describe.**
We use V1 for our django deployment on EBS.
Since the docker file on V1 doesn't have "apt-get -y", our action is always failing.

**Describe the solution you'd like**
TOT has "install -y", just releasing a new version would do.

**Describe alternatives you've considered**
1. Forking myself and creating a new version.

**Additional context**
N/A

**Comment by Joel-hanson** [comment]
@kpadalkar can please share the screenshot or the log for this issue.

**Comment by kpadalkar** [comment]
[logs_64.zip](https://github.com/Joel-hanson/django-aws-eb-deploy/files/4671204/logs_64.zip)
Added the logs...

**Comment by Joel-hanson** [comment]
@kpadalkar I have made a change to the part which you had the issue. can you please try now.

The version is still the same `V1`

**Comment by kpadalkar** [comment]
Is V1 published again?
Because I still see the same issue on V1

I use it as follows-

```
    - name: Django aws eb deployment
      uses: joel-hanson/django-aws-eb-deploy@V1
      with:
        python_version: ${{ matrix.python_version }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
        django_path: <product_dir>
        unit_testing: false
        flake8: false
        deploy: true
```
